#ifndef COMMON_H
#define COMMON_H

#include <stddef.h>

#define HASH_SIZE 32 // Assuming this is defined in smt.h; adjust if different

typedef enum {
    DB_SUCCESS = 0,
    DB_ERROR_NULL_POINTER = -1,
    DB_ERROR_MEMORY_ALLOCATION = -2,
    DB_ERROR_INVALID_PARAMETER = -3,
    DB_ERROR_KEY_NOT_FOUND = -4,
    DB_ERROR_DATABASE_NOT_FOUND = -5,
    DB_ERROR_COLLECTION_NOT_FOUND = -6,
    DB_ERROR_DATABASE_EXISTS = -7,
    DB_ERROR_COLLECTION_EXISTS = -8,
    DB_ERROR_MAX_LIMIT_REACHED = -9,
    DB_ERROR_INVALID_JSON = -10,
    DB_ERROR_CONCURRENT_ACCESS = -11,
    DB_ERROR_DATABASE_CLOSED = -12,
    DB_ERROR_IO_ERROR = -13,
    DB_ERROR_CORRUPTED_DATA = -14,
    DB_ERROR_INVALID_STATE = -15,
    DB_ERROR_SMT_FAILED = -16,
    DB_ERROR_LOCK_TIMEOUT = -17,
    DB_ERROR_LOCK_FAILED = -18,
    DB_ERROR_INDEX_NOT_FOUND = -19,
    DB_ERROR_SSTABLE_LIMIT = -20
} db_error_t;

#endif // COMMON_H